name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Verify python version
        run: python --version  