name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Verify Docker
        run: docker --version
      
      - name: Verify Docker Compose
        run: docker compose version

      #Create a temporal env file in the Github machine
      - name: Prepare CI environment file
        run: cp .env.example .env

      - name: Validate Docker Compose Configuration
        run: docker compose --env-file .env.example config --quiet

      # create the app image
      - name: Build application image
        run: docker compose build app